version: '3.8'

services:
  # 1. PostgreSQL Database Container
  db:
    image: postgres:15-alpine
    container_name: ldc_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: lakshmi_dental_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. NestJS Backend Container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ldc_backend_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/lakshmi_dental_db?schema=public
      - JWT_SECRET=LDC_SuperSecureEnterpriseClinicKey7739!
      - PORT=3000
    depends_on:
      - db

  # 3. Next.js Frontend Container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ldc_frontend_web
    restart: always
    ports:
      - '80:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data:
